from django.conf.urls.defaults import *
from Demo.cmdb.views import *


urlpatterns = patterns('',
    url(r'^login/$',loginindex),
    url(r'^bj/$',bj),
    url(r'^bjlist/$',bjlist),
    url(r'^zhsearch/$',zhsearch),
    url(r'^crvm/$',crvm),
    url(r'^reg/$',register),
    url(r'^randompasswd/$',randompasswd),
    url(r'^$', foobar_view, {'template_name': 'index.html'}),
    url(r'home/$', foobar_view, {'template_name': 'index.html'}),
    url(r'nav/$', foobar_view, {'template_name': 'nav.html'}),
    url(r'searchindex/$', foobar_view, {'template_name': 'searchindex.html'}),
    url(r'newbj/$', foobar_view, {'template_name': 'newbj.html'}),
    url(r'newdailywork/$', foobar_view, {'template_name': 'dailywork.html'}),
    url(r'newvm/$', foobar_view, {'template_name': 'createvm.html'}),
    url(r'savedailywork/$',save_dailywork),
    url(r'getvpnuser/$',getvpnuser),
    url(r'getvipvpnuser/$',getvipvpnuser),
    url(r'delvipvpnuser/$',delvipvpnuser),
    url(r'getdisablevpnuser/$',getdisablevpnuser),
    url(r'generatedisablevpn/$',generatedisablevpn),
    url(r'ipaviable/$',ipaviable),
    url(r'GenerateVpnInform/$',GenerateVpnInform),
    url(r'sendmail/$',sendmail),
    url(r'vpndisable/$',vpndisable),
    url(r'loginauth',login_view),
    url(r'logout/$',logout),
    url(r'outputrecords/$',outrecords),
    url(r'userfunc/$',userfunc),
    url(r'updatefunc/$',updatefunc),
    url(r'daily_work_list/$',daily_work_list),
    url(r'generatequote/$',generatequote),
)